### ISSUE TITLE
一点儿建议

### ISSUE THREAD

**Issue by hadix-lin** [bitprince/memory#1]
没有使用过你的项目,不过看了你的readme我对memory很感兴趣,我也不喜欢hibernate这种重型工具,Dbutils是我常用的.
以下一点儿建议:
1.项目源码里面不要包含你的本地依赖的配置文件,比如开发环境相关的".project,.classpath"等.
2.使用gradle,maven这样的标准构建工具管理你的项目.
3.Statement和CallableStatement真的没意义吗?我觉得作为一个工具应当提供支持,总是有人需要,而且不少.特别是遗留项目中.
4.你的pager方法第一个参数是StringBuffer,为什么?为什么不是StringBuilder?
5.既然是个新项目何不考虑使用一下java8的新特性,看看有没有可以让接口变的更简单的方法.我不是说java8的特性一定有帮助,但是考察一下无妨.

**Comment by bitprince** [comment]
谢谢您的建议！
1. 提交的时候应该ignore。下次注意。
2. 项目太小，有点用牛刀杀小鸡的感觉。在大项目中可以考虑使用。gradle我还没用过，真是土人1个。有机会试一试，多谢推荐。
3. 在我们的项目也有使用，就是从memory获取连接后，使用最原始jdbc写法去使用statement和callabeStatement，只是memory没有做任何封装。
4. StringBuffer, 线程安全，StringBuilder则不然。当然如果能确保是单线程环境，用StringBuilder效率更高一些。sonar质量分析也指出了这个问题。
5. Lambda表达式，可以把方法当作参数用，在ResultHandler自定义为匿名类时，写法确实简化不少。但是写memory时在两年前，而java8去年才发布。

**Comment by hadix-lin** [comment]
一般项目中使用数据库连接池，单线程独占连接执行事务，分页语句也是在这个线程里面。谢了这么多年Java，真的一次StringBuffer都没用过。
